### PR TITLE
update(i18n, git): locales for `zh-Hans` and `.gitignore` file

### PR DESCRIPTION
**Pull request by baysonfox**

### CODE REVIEW

**Comment by haren724** [comment]
Have you tested the localization file you refactored? Does it take effect on Xcode 14?

I'm using beta software, so it's a little difficult to test this. Hope you can help me.

**Comment by baysonfox** [comment]
> Have you tested the localization file you refactored? Does it take effect on Xcode 14?
> 
> I'm using beta software, so it's a little difficult to test this. Hope you can help me.

Using Xcode-beta and Sonoma too, just added some missing translations, so no support for Xcode 14 IMO.

**Comment by haren724** [comment]
Okay I just got misunderstood. 😂

**Review by haren724 — APPROVED** [review]
'APPROVE' performed by Xcode.

**Pull request merged**
